server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json

spring:
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: 0

  application:
    name: tk-classified-ads-platform
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false
  
  main:
    lazy-initialization: true
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.EmbeddedDatabaseConnectionAutoConfiguration

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000

    ads:
        jdbc-url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tk_ads}
        username: ${DB_USER:ads_god}
        password: ${DB_PASSWORD:87654321}
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 60000
        connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master.yml
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tk_ads}
      user: ${DB_USER:ads_god}
      password: ${DB_PASSWORD:87654321}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

image:
  avatar:
    min-file-size-bytes: 100
    max-file-size-bytes: 10485760
    min-width: 64
    min-height: 64
    max-width: 1920
    max-height: 1080
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/webp
    io-buffer-size: 10485760
    url-base-path: /users/avatar
    storage-path: /home/kostus/ad-avatar
    file-name-default: "classpath:static/watto.jpg"
    file-size-default: 39564
    mime-type-default: image/jpeg

  ad:
    min-file-size-bytes: 512
    max-file-size-bytes: 10485760
    min-width: 256
    min-height: 256
    max-width: 2048
    max-height: 2048
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/webp
    io-buffer-size: 10485760
    url-base-path: /ads/image
    storage-path: /home/kostus/ad-image
    file-name-default: "classpath:static/no-image.png"
    file-size-default: 45061
    mime-type-default: image/png

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers,threaddump,prometheus

logging:
  level:
    org:
      hibernate: ERROR
      springframework:
        data:
          jpa: ERROR

cors:
  allowed-origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
    - "http://localhost:80"
    - "http://web:3000"
    - "http://web:80"
