# https://www.javaguides.net/2025/03/spring-boot-performance-tuning.html
server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json

spring:
  application:
    name: tk-classified-ads-platform
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  main:
    lazy-initialization: true
  autoconfigure:
      exclude: org.springframework.boot.autoconfigure.jdbc.EmbeddedDatabaseConnectionAutoConfiguration

  datasource:
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000

    ads:
        jdbc-url: jdbc:postgresql://localhost:5432/tk_ads
        username: ads_god
        password: 87654321
        maximum-pool-size: 20
        minimum-idle: 5
        idle-timeout: 30000
        max-lifetime: 60000
        connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master.yml
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tk_ads
      user: ads_god
      password: 87654321

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

image:
  avatar:
    min-file-size-bytes: 100
    max-file-size-bytes: 10485760
    min-width: 64
    min-height: 64
    max-width: 1920
    max-height: 1080
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/webp
    io-buffer-size: 10485760
    url-base-path: /users/avatar
    storage-path: /home/kostus/ad-avatar
  ad:
    min-file-size-bytes: 512
    max-file-size-bytes: 10485760
    min-width: 256
    min-height: 256
    max-width: 2048
    max-height: 2048
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/webp
    io-buffer-size: 10485760
    url-base-path: /ads/image
    storage-path: /home/kostus/ad-image

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers,threaddump,prometheus
