server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: tk-classified-ads-platform
  sql:
    init:
      mode: never
  output:
    ansi:
      enabled: always
  thymeleaf:
    check-template-location: false

  datasource:
    ads:
        jdbc-url: jdbc:postgresql://localhost:5432/tk_ads
        username: ads_god
        password: 87654321
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  liquibase:
      enabled: true
      change-log: classpath:db/changelog/changelog-master.yml
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/tk_ads
      user: ads_god
      password: 87654321

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

validation:
  image:
    min-file-size-bytes: 100
    max-file-size-bytes: 10485760
    min-width: 64
    min-height: 64
    max-width: 1920
    max-height: 1080
    allowed-mime-types:
      - image/jpeg
      - image/png
      - image/webp

media:
  avatar-url-base-path: /users/avatar
  avatar-storage-path: /home/kostus/ad-user-avatar
  image-url-base-path: /ads/image
  image-storage-path: /home/kostus/ad-image
  io-buffer-size: 10485760

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers,threaddump,prometheus
